name: Project Management

on:
  issues:
    types:
      - opened
      - reopened
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  add-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vtisweden'
    steps:
      - uses: vtisweden/action-project-management@main
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          organization: vtisweden
          project-number: 16
          issue-pr-id: ${{ github.event.issue.node_id || github.event.pull_request.node_id }}
          event-name: ${{ github.event_name }}
